### PR TITLE
Add publisher field type

### PR DESCRIPTION
**Pull request by jmudge**

### CODE REVIEW

**Review by jpradocueva — COMMENTED** [review]
Can we move "publisher" up in the structure and swap it with "name" inside of the "organization" object?

**Comment by jmudge** [comment]
@jpradocueva in order to support the general case of including documents in a release that have been published elsewhere wouldn't the publisher need to be at the individual document (items) level? It is possible that some OMA releases include files published elsewhere, or that there may be a requirement to do so in the future. Also don't the IEEE want to know the publisher of each individual document as per their sample data?

**Comment by jpradocueva** [comment]
@jmudge the baseline in "master" has evolved with some changes and the PR indicates that there is a conflict. I am not sure how to resolve the conflict without introducing further errors so I wonder if you can do a Pull from your PR to bring the latest changes before applying your "publisher" addition. Thanks

**Comment by jmudge** [comment]
@jpradocueva thank you for the notification. There seem to be 3 schema files in the master branch now; which file should the PR update?

**Comment by jpradocueva** [comment]
The baseline documents are the original ones:
* ddf_oma_library.json, and
* oma_ddf_oma_library.json
I have added a new draft baseline for the API,
* openapi-example.json
I am using this file to learn about oneapi; I will create a new baseline based on this example.

I will copy this content in the README file to make it clear.

**Comment by jmudge** [comment]
A replacement PR may be submitted.

**Comment by jpradocueva** [comment]
Thanks, John, I am planning to finalize the schema and json file once I complete the work with the API. It means that you have time but please don't delay it.

**Pull request closed without merging**
